### ISSUE TITLE
License on flathub just says "free"

### ISSUE THREAD

**Issue by jeremiah** [flathub/com.jgraph.drawio.desktop#13]
Looking at the meta data files on Github it looks as if draw.io code is licensed under the Apache 2.0 license. But on flathub it just says "free". Should the license be specified on flathub with more precision? That might help people who don't know what "free" means in this context or who may want to know specifically which license the code is under before downloading. Thanks!

**Comment by ghisvail** [comment]
Please report your findings to the Flathub issue tracker. The [licensing metadata](https://github.com/flathub/com.jgraph.drawio.desktop/blob/61085c178ea8b463d965b437e8597f928d5ea623/com.jgraph.drawio.desktop.appdata.xml#L6) for the project are correctly set.

**Comment by TingPing** [comment]
This is already reported here: https://github.com/flathub/linux-store-frontend/issues/143
