### ISSUE TITLE
Getting verified

### ISSUE THREAD

**Issue by JamesBelchamber** [flathub/com.jgraph.drawio.desktop#136]
I think this app is official - if so, could we get it verified? Instructions are [here](https://docs.flathub.org/docs/for-app-authors/verification).

**Comment by davidjgraph** [comment]
If by official you mean it's endorsed by the core draw.io team, it's not.

**Comment by davidjgraph** [comment]
I merely link here, this being the only implementation.

**Comment by JamesBelchamber** [comment]
Fair enough. David I just noticed that you're part of the team there - is there any way this could be promoted to a first-class release of draw.io? I see that snaps and AppImages are "endorsed" already.

It would be great to get this app verified on the Flathub store!

**Comment by davidjgraph** [comment]
Not as draw.io, unfortunately. We're SOC 2 as a company, we can only say something is ours if we fully control the release process.

It could be published under a different name (e.g. diagrams) and without logo.

**Comment by JamesBelchamber** [comment]
Hmm, interesting. I'm sure this isn't the only project with that problem on Flathub. I wonder how it differs from e.g. the App Store or the Play Store?

Anyway, you probably know more about this than me. I would like to see it verified, but if this is not possible (or, possible but not desirable) then feel free to close off this issue :)

**Comment by ghisvail** [comment]
> We're SOC 2 as a company, we can only say something is ours if we fully control the release process.

Closing as won't fix then.
