### ISSUE TITLE
Serious rendering issue on fedora 38 & 39

### ISSUE THREAD

**Issue by siddheshgunjal** [flathub/com.jgraph.drawio.desktop#154]
**Describe the bug**
After the recent system update there are serious rendering issues. The app is completely unusable. I love using this app and shifting again to web version is hassle.

**To Reproduce**
1. Go to  Draw.io in Fedora Software app or in Flathub
2. Install the Flathub version
3. Launch the application
4. You will see app is not rendering anything properly

**Expected behavior**
Render everything properly as its seen on webapp on browser

**Screenshots**
![Screenshot from 2023-11-09 11-06-46](https://github.com/jgraph/drawio-desktop/assets/37741186/7ec03da0-8c0c-4fe7-9f45-dad260d0cac5)
![Screenshot from 2023-11-09 11-07-38](https://github.com/jgraph/drawio-desktop/assets/37741186/38b32e74-2fbd-432c-8526-053b0a42679f)
![Screenshot from 2023-11-09 11-07-56](https://github.com/jgraph/drawio-desktop/assets/37741186/8ef842b0-7ecd-4e31-9aa9-f65b9576d534)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version: 22.0.3

**Desktop (please complete the following information):**

#### Hardware Information:
- **Hardware Model:**                              Lenovo Lenovo ideapad 330S-14IKB U1
- **Memory:**                                      8.0 GiB
- **Processor:**                                   Intel® Core™ i5-8250U × 8
- **Graphics:**                                    Intel® UHD Graphics 620 (KBL GT2)

#### Software Information:
- **OS Name:**                                     Fedora Linux 39 (Workstation Edition)
- **OS Type:**                                     64-bit
- **GNOME Version:**                               45.1
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.5.10-300.fc39.x86_64

**Additional context**

**Comment by jprenaudet** [comment]
I'm under linux mint 21.1 Cinnamon Edition under X11.
Using FlatSeal I was able to make rendering ok using this workaround :  
- in `Device -> GPU acceleration` : deactivate ability to use this device (device=dri).

Don't know if it will work for you, but you could give a try :)

**Comment by siddheshgunjal** [comment]
@jprenaudet Thanks for your suggestions. Today when I tried it, it was automatically resolved. Maybe after the recent system update one of the package responsible fixed it's issue.
