### ISSUE TITLE
When the DrawIO program starts, the complete GUI is blank and distorted. Unable to use it. 

### ISSUE THREAD

**Issue by fredygamez** [flathub/com.jgraph.drawio.desktop#155]
![image](https://github.com/flathub/com.jgraph.drawio.desktop/assets/17584642/b94940c3-37d9-4362-b739-c3c3809c5a24)

When it starts, there is no picture of icons and the environment are completely blurry and there are no menus or icons. On November 15, 2023, the Flatpak packages were updated, but DrawIO still doesn't start properly.  Ubuntu 20.04.

**Comment by fredygamez** [comment]
![image](https://github.com/flathub/com.jgraph.drawio.desktop/assets/17584642/51c32b23-e36b-4e83-ae69-f13d32373b7b)
The image turns black after resizing the window, as well as the previous issue.

**Comment by ghisvail** [comment]
Try closing the app, deleting its GPU cache, and restarting it:

`rm -rf ~/.var/app/com.jgraph.drawio.desktop/config/draw.io/GPUCache/`

**Comment by fredygamez** [comment]
thanks [ghisvail](https://github.com/ghisvail) that works perfect, now the GUI is back to normal.
