### ISSUE TITLE
Bug: draw.io (flatpak) no longer usable with 11.1.1 release

### ISSUE THREAD

**Issue by daniel-wtd** [flathub/com.jgraph.drawio.desktop#16]
Since the release of draw.io 11.1.1, all older version redirect to the github page and are no longer usable. It would be awesome to see an update.

https://github.com/jgraph/drawio-desktop/releases

![Screenshot from 2019-08-06 10-25-48](https://user-images.githubusercontent.com/6490538/62523740-b40be780-b834-11e9-8ef4-2987c36cb897.png)

**Comment by ghisvail** [comment]
Would fix #12 in the process.

**Comment by davidjgraph** [comment]
Sorry, forgot about this one. The security issue is pretty serious, thus the lockdown. What do you need for a PR?

**Comment by ghisvail** [comment]
I'll make the update soon.

**Comment by ghisvail** [comment]
Could you guys test the candidate version in https://github.com/flathub/com.jgraph.drawio.desktop/pull/17 ?

**Comment by ghisvail** [comment]
Gonna merge it anyway and let you guys report any issues here.

It looked good on a local build.

**Comment by daniel-wtd** [comment]
updated, launched, seems to work.

thank you a ton :)
