### ISSUE TITLE
Uniform metadata between stores

### ISSUE THREAD

**Issue by ghisvail** [flathub/com.jgraph.drawio.desktop#18]
See description and summary in the Chrome store:

https://chrome.google.com/webstore/detail/drawio-desktop/

**Comment by ghisvail** [comment]
@davidjgraph, should I consider the metadata in the Chrome store as the official one?

**Comment by ghisvail** [comment]
@davidjgraph, do you know where the screenshots from the Chrome store page come from ? I'd like to use these for Flathub / GNOME Software.

**Comment by davidjgraph** [comment]
Chrome store is good as any, but our text is very basic, always room for improvement.

Screenshots aren't in public repo, yet, attached.

[screenshots.zip](https://github.com/flathub/com.jgraph.drawio.desktop/files/3502371/screenshots.zip)

**Comment by ghisvail** [comment]
Not much to be done here anymore.
