### ISSUE TITLE
Can't find ref com.jgraph.drawio

### ISSUE THREAD

**Issue by x80486** [flathub/com.jgraph.drawio.desktop#2]
When we search via the command-line for `draw.io desktop`, it's returned like this:

```
[gorre@uplink ~]$ flatpak search drawio
Application ID    Version Branch Remotes Description                                              
com.jgraph.drawio 8.6.5   stable flathub draw.io is an open platform to create and share diagrams.
```

Eventually, the application cannot be installed, because it's registered as: `com.jgraph.drawio.desktop`.

**Comment by TingPing** [comment]
This is a bug in appstream-glib: https://github.com/hughsie/appstream-glib/blob/b1cdc4d04875c3a93161266fc4b9737c157d152a/libappstream-glib/as-app.c#L2264-L2302

It strips `.desktop` suffix from app-ids unconditionally it seems. (`.desktop` being part of the id has always caused issues...)

**Comment by TingPing** [comment]
Hmm, it does work for `org.telegram.desktop` though, so maybe I'm missing something or a workaround.

**Comment by ghisvail** [comment]
Not sure what's actionable on my end here?
