### ISSUE TITLE
Unable to pass CLI arguments to draw.io

### ISSUE THREAD

**Issue by rombert** [flathub/com.jgraph.drawio.desktop#25]
Draw.io also has a CLI interface which allows for better automated usage, e.g.

    draw.io -x -f svg -o Diagram.svg Diagram.drawio 

However, if I try to run the flatpak the CLI arguments are ignored. Running

    flatpak run com.jgraph.drawio.desktop -V

or

    flatpak run com.jgraph.drawio.desktop -x -f svg -o Diagram.svg Diagram.drawio

Results in the program being ran as usual.

For various automation tasks it would be great if the flatpak would also be usable as a CLI.

**Comment by ghisvail** [comment]
Actually, this [PR](https://github.com/flathub/com.jgraph.drawio.desktop/pull/29) might have solved your issue already. Could you please verify whether the issue is still present on the current version?

Cheers.

**Comment by rombert** [comment]
@ghisvail - indeed, this works now! I verified it with both versions 12.4.0 and 12.9.3
