### ISSUE TITLE
Requires the SDK runtime?

### ISSUE THREAD

**Issue by Wowfunhappy** [flathub/com.jgraph.drawio.desktop#3]
Hi,

When I installed this application from flathub, I noticed that it required the org.freedesktop.**Sdk** runtime. This surprised me; aren't the SDK runtimes usually needed for development only?

If this is not a bug, feel free to close. However, I wanted to flag it. :)

**Comment by ghisvail** [comment]
It should be `Platform`, indeed. Thanks for flagging it!
