### ISSUE TITLE
drawio-desktop doesn't start when using application icon

### ISSUE THREAD

**Issue by x80486** [flathub/com.jgraph.drawio.desktop#32]
After the last update, something is _wonky_ with `drawio-desktop` if started via the (usual) desktop icon:

```shell
Apr 04 22:54:51 uplink systemd[778]: Started Application launched by gnome-shell.
Apr 04 22:54:51 uplink systemd[778]: Started flatpak-com.jgraph.drawio.desktop-179608.scope.
Apr 04 22:54:51 uplink systemd[778]: gnome-launched-com.jgraph.drawio.desktop.desktop-179608.scope: Succeeded.
Apr 04 22:54:51 uplink com.jgraph.drawio.desktop.desktop[179621]: bwrap: execvp start-drawio-desktop: No such file or directory
Apr 04 22:54:51 uplink systemd[778]: flatpak-com.jgraph.drawio.desktop-179608.scope: Succeeded.
```

The application doesn't start, and that's all you have in the logs that the `journald` daemon collected. To make things more interesting, if the application is started via `flatpak run com.jgraph.drawio.desktop` it runs fine.

I'm using Arch Linux, but probably that shouldn't matter...much:

```
[x80486@uplink:~]$ uname -a
Linux uplink 5.4.28-2-lts #1 SMP Mon, 30 Mar 2020 19:30:28 +0000 x86_64 GNU/Linux
```

**Comment by ghisvail** [comment]
It works fine with both the application icon and launching via `flatpak run` on my machine. I have got no idea what's going on in your system, though this:

```
Apr 04 22:54:51 uplink com.jgraph.drawio.desktop.desktop[179621]: bwrap: execvp start-drawio-desktop: No such file or directory
```

looks quite suspicious as it's supposed to be **start-drawio**.

**Comment by x80486** [comment]
Forgot to update this issue. I just uninstall it with `--delete-data` and reinstall it...everything is fine.
