### ISSUE TITLE
App installed does not show in the Open With list

### ISSUE THREAD

**Issue by Melvasul** [flathub/com.jgraph.drawio.desktop#34]
![image](https://user-images.githubusercontent.com/11297488/80684450-fe6d7c80-8ac5-11ea-8162-0cf5955fa7d5.png)

Hello there
Fedora 32 on a Thinkpad E485 (Ryzen APU powered) here, latest kernel
I've installed Draw.io using Flatpak, as from here: https://flathub.org/apps/details/com.jgraph.drawio.desktop
simply because it's the easiest and best way possible.

I really enjoyed its access to the folders and files in /home/ (something not always pre-available in many flatpak apps) but there's a problem:
When I go and try to select draw.io as the app to open the *draw.io files the app is simply not there :/

I've seen that all the other apps I've installed through flatpak are there though :|

Thanks in advance,
have a nice day :)

**Comment by ghisvail** [comment]
It's probably missing some mime type registration in the desktop or metainfo file. I will investigate.

**Comment by ghisvail** [comment]
Should be fixed by #45
