### ISSUE TITLE
Build this flatpak from source

### ISSUE THREAD

**Issue by ghisvail** [flathub/com.jgraph.drawio.desktop#4]
As commented in the initial PR for `com.jgraph.drawio.desktop`, it would be desirable to build this flatpak from source as opposed to basing it off the Debian packages.

**Comment by davidjgraph** [comment]
What is actionable on our part to achieve that?

**Comment by ghisvail** [comment]
@nedrichards I have tried to build this flatpak from source and was actually successful, thanks to your tutorial on the `electron-simple-app`. However, building the application from source does not seem to generate the necessary desktop integration files and icons (.desktop file under `$PREFIX/share/applications/`and .png files under `$PREFIX/share/icons/...`). Does it have to be implemented manually then?

**Comment by ghisvail** [comment]
@davidjgraph Not much on your end as it's more of an experiment at this point. I'll keep you posted with the details once I have got something ready. Sounds good?
