### ISSUE TITLE
Mimetype not exported

### ISSUE THREAD

**Issue by 73** [flathub/com.jgraph.drawio.desktop#43]
I run Ubuntu 20.10 with a draw.io from flathub.
The mimetype of my `.drawio` files are picked up as being `plain text document`.

![image](https://user-images.githubusercontent.com/529346/104307119-232c4780-54cf-11eb-9ba6-0130ca1c2e4f.png)

However, the mimetype description is contained within the flatpak but not picked up.
I assume the package needs to fit the definition [somehow](https://github.com/flatpak/flatpak/issues/1572).

Thanks for making a package!

**Comment by 73** [comment]
Works. Thanks!

**Comment by 73** [comment]
This problem reappeared. Can we reopen this?

**Comment by ghisvail** [comment]
@davidjgraph could you tell where the mime package is generated when building from source? Is it handled transparently by electron-builder or is there another step to generate it?

**Comment by davidjgraph** [comment]
It's automatically handled by electron-builder, https://github.com/jgraph/drawio-desktop/blob/master/electron-builder-linux-mac.json
