### ISSUE TITLE
Bug: No such file or directory

### ISSUE THREAD

**Issue by daniel-wtd** [flathub/com.jgraph.drawio.desktop#49]
Hi, since the last update I am facing the below behavior.

```
flatpak run com.jgraph.drawio.desktop
[2 zypak-helper] exec failed for /app/draw.io/drawio: No such file or directory (errno 2)
```

**Comment by ghisvail** [comment]
Fixed with https://github.com/flathub/com.jgraph.drawio.desktop/commit/76cd5c1af18f922dd7c63b98baf83b792ba98a98

**Comment by daniel-wtd** [comment]
thanks a lot, awesome!
