### ISSUE TITLE
Wrong StartupWMClass in .desktop file

### ISSUE THREAD

**Issue by derscott** [flathub/com.jgraph.drawio.desktop#52]
Hi,

there is an error in the `com.jgraph.drawio.desktop.desktop` located in `/var/lib/flatpak/app/com.jgraph.drawio.desktop/current/active/export/share/applications`:
```
StartupWMClass=drawio
```
The actual WM_CLASS of the window (determined via running `xprop WM_CLASS`) is
```
WM_CLASS(STRING) = "draw.io", "draw.io"
```

This caused having a separate icon referring to the running application next to the actual launcher.
![Auswahl_061](https://user-images.githubusercontent.com/16992666/116690858-4d404180-a9ba-11eb-9c93-24c8bf6ecf82.png)

**Comment by ghisvail** [comment]
Hi, thanks for investigating. Feel free to submit a PR.
