### ISSUE TITLE
Add keywords to .desktop file

### ISSUE THREAD

**Issue by wjt** [flathub/com.jgraph.drawio.desktop#68]
I wanted to draw a flow chart, and I knew I had a suitable tool installed, but could not remember what it was called. I used GNOME Shell's desktop search to search for "flow", "flowchart", "chart", and got no results for each. Finally I tried "diagram" and that worked.

I suggest adding some keywords to the `.desktop` file for diagram-related words, such as:

```
Keywords=flow;flowchart;org;process;uml;entity;network;chart;diagram
```

This will cause the app to show up in desktop searches for these terms, and also in GNOME Software searches for these terms (if it is not installed).

Ideally these (and the `.desktop` file) would go upstream, and be localised by the same process by which the app is localised. e.g. my bad french suggests:

```
Keywords[fr]=flux;entité;relation;diagramme;…
```

**Comment by ghisvail** [comment]
Le jeu. 22 juil. 2021 à 12:32, Will Thompson ***@***.***> a
écrit :

> I wanted to draw a flow chart, and I knew I had a suitable tool installed,
> but could not remember what it was called. I used GNOME Shell's desktop
> search to search for "flow", "flowchart", "chart", and got no results for
> each. Finally I tried "diagram" and that worked.
>
> I suggest adding some keywords to the .desktop file for diagram-related
> words, such as:
>
> Keywords=flow;flowchart;org;process;uml;entity;network;chart;diagram
>
>
> This will cause the app to show up in desktop searches for these terms,
> and also in GNOME Software searches for these terms (if it is not
> installed).
>
> Ideally these (and the .desktop file) would go upstream, and be localised
> by the same process by which the app is localised. e.g. my bad french
> suggests:
>
> Keywords[fr]=flux;entité;relation;diagramme;
>
>
Indeed, please submit these upstream 👍

**Comment by wjt** [comment]
As far as I can tell upstream does not have a `.desktop` file, and it's the one in this repo which is used:

https://github.com/flathub/com.jgraph.drawio.desktop/blob/master/com.jgraph.drawio.desktop.yaml#L49

I'm afraid I don't have the cycles to propose a `.desktop` file upstream.
