### ISSUE TITLE
Drawio doens't render

### ISSUE THREAD

**Issue by vorlock** [flathub/com.jgraph.drawio.desktop#7]
Looks like this app is having issues with rendering on tiling window managers like awesome. There is not much to go with really. I tried to debug it  bit but being not a big fan of js I didn't manage to really dig into it.

But if some additional info is needed I'm keen trying again if given a bit of guidance on what to look for.

**Comment by ghisvail** [comment]
Is that an issue you're having with all Electron-based flatpak apps, or this one only?

**Comment by davidjgraph** [comment]
What are the environment setup/action steps to recreate?

**Comment by vorlock** [comment]
@ghisvail I just installed VS Code (as far as I know it's also Electron) and this one looks good.

@davidjgraph sorry for the lack of details (I have no idea why I didn't provide those)

```
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux testing (buster)
Release:	testing
Codename:	buster

awesome      4.2-5    amd64 highly configurable X window manager
flatpak      1.0.4-1  amd64 Application deployment framework for desktop apps
xserver-xorg 1:7.7+19 amd64 X.Org X server

Ref                                                Options
com.jgraph.drawio.desktop/x86_64/stable            current
com.slack.Slack/x86_64/stable                      current
com.visualstudio.code.oss/x86_64/stable            current
org.freedesktop.Platform.Compat.i386/x86_64/18.08  runtime
org.freedesktop.Platform.VAAPI.Intel/x86_64/1.6    runtime
org.freedesktop.Platform.VAAPI.Intel/x86_64/18.08  runtime
org.freedesktop.Platform.ffmpeg/x86_64/1.6         runtime
org.freedesktop.Platform.html5-codecs/x86_64/18.08 runtime
org.freedesktop.Platform/x86_64/18.08              runtime
org.freedesktop.Sdk/x86_64/1.6                     runtime
org.freedesktop.Sdk/x86_64/18.08                   runtime
```

**Comment by ghisvail** [comment]
@vorlock could you provide a screenshot of the rendering problem, please?

**Comment by vorlock** [comment]
Unfortunately I can't, I switched to AppImage to be able to use it

**Comment by ghisvail** [comment]
Glad to hear you found a solution. I'll close the issue then, as I see no
path forward.

**Comment by vorlock** [comment]
I can do it for you, thanks.
