### ISSUE TITLE
Import Visio stencils (VSS)

### ISSUE THREAD

**Issue by vincentbernat** [flathub/com.jgraph.drawio.desktop#88]
Hey!

From draw.io, I am able to import Visio Stencils when using "File → New Library → From Device". However, the same does not work with the Flatpak app. I get a "Service unavailable or blocked" error message instead:

![image](https://user-images.githubusercontent.com/631446/144840274-750987eb-b0df-4c13-a2ad-e0715bb61448.png)

You can download VSS from [Cisco](https://www.cisco.com/c/en/us/products/visio-stencil-listing.html).

A workaround is to use the online version to create the library and export it to the drawio format.

**Comment by davidjgraph** [comment]
The desktop apps are isolated, they are designed not to transmit data.

**Comment by vincentbernat** [comment]
You mean the conversion from VSS format is done by a service online?

**Comment by davidjgraph** [comment]
Binary vss and vsd are converted to the current XML format on a server and the XML is converted locally. If you load the VSS up in a modern Visio version, you can re-save it to vssx and import that.

**Comment by vincentbernat** [comment]
Thanks for the insight. Let's close this as this works as expected.
